version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: proj_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=projApiMongoDB
      - MongoDbSettings__InfectadosCollectionName=infectados

volumes:
  mongo_data:
